<a href="https://colab.research.google.com/github/Harishrsharma/udemy-exercise/blob/main/Udemy13_08_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Sales###


In [4]:
print("Hello Welcome")

Hello Welcome


In [5]:
revenue = 10000
tax = 0.18
income = revenue * tax
income

1800.0

In [6]:
print(income)

1800.0


In [3]:
import numpy as np

np.__version__


'1.21.6'

In [8]:
np.random.rand(2,2)

array([[0.55933765, 0.59443687],
       [0.15530909, 0.09238078]])

In [9]:
import imageai

ModuleNotFoundError: ignored

In [10]:
!pip install imageai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 160 kB 8.4 MB/s 
     |████████████████████████████████| 2.1 MB 65.2 MB/s 
     |████████████████████████████████| 14.9 MB 43.1 MB/s 
     |████████████████████████████████| 26.1 MB 1.5 MB/s 
     |████████████████████████████████| 2.9 MB 38.9 MB/s 
     |████████████████████████████████| 11.6 MB 34.2 MB/s 
  Created wheel for keras-resnet: filename=keras_resnet-0.2.0-py2.py3-none-any.whl size=20486 sha256=8f6cbcd8a81fa75d584507dffcceaca7a7c84c2e4571a0f7258e55504987d33d
  Stored in directory: /root/.cache/pip/wheels/bd/ef/06/5d65f696360436c3a423020c4b7fd8c558c09ef264a0e6c575
Successfully built keras-resnet
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.3
    Uninstalling scip

In [11]:
import imageai

In [1]:
import numpy as np

MarkDown

>Python
>>>Code

[Google](http:www.Google.com)

![python](https://logos-world.net/wp-content/uploads/2021/10/Python-Symbol.png)

$ y = x^2 $

$\frac{1}{2} \sum_{i=1}^{n}x_{i}$

$ A = \begin{pmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end {pmatrix} $ 


Col1 |Col2 |col3
--- |--- |---
val1 |val2 |val3 


**np.all** function


###np all###
*italicized text* function is to find logical and operation and return a boolean value axis 0 = comparing column and axis=1 row it return True if every element in array is non zero else vice versa


In [2]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')





A: True
B: False
C: False
D: True


In [4]:
print(np.all(A))
print(np.all(B))
print(np.all(B))
print(np.all(D))

True
False
False
True


In [5]:
print(np.all([[True,False],[True,False],[True,True],[True,False]],axis=-1))
print(np.all([[True,True],[True,True],[True,True],[True,False]],axis=0))
print(np.all([[True,False],[True,False],[True,True],[True,False]],axis=1))




[False False  True False]
[ True False]
[False False  True False]


###numpy.allclose###
**numpy.allclose
** *italicized text*Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers. The relative difference (rtol * abs(b)) and the absolute difference atol are added together to compare against the absolute difference between a and b.

NaNs are treated as equal if they are in the same place and if equal_nan=True. Infs are treated as equal if they are in the same place and of the same sign in both arrays.

In [6]:
  import numpy as np


A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print(np.allclose(A,B))



True


###Numpy.zeros###
Return a new array of given shape and type, filled with zeros.

Parameters
shapeint or tuple of ints
Shape of the new array, e.g., (2, 3) or 2.

dtypedata-type, optional
The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

order{‘C’, ‘F’}, optional, default: ‘C’
Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

likearray_like, optional
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.



In [7]:
print(np.zeros((4,4),dtype=int))


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**numpy.ful**l(shape, fill_value, dtype=None, order='C', *, like=None)[source]
Return a new array of given shape and type, filled with fill_value.

Parameters
shapeint or sequence of ints
Shape of the new array, e.g., (2, 3) or 2.

fill_valuescalar or array_like
Fill value.

dtypedata-type, optional
The desired data-type for the array The default, None, means
np.array(fill_value).dtype.

order{‘C’, ‘F’}, optional
Whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory.

likearray_like, optional
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

In [8]:
import numpy as np
 
 
print(np.full(shape=(10, 10), fill_value=255, dtype='float'))



[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


###numpy.ones###
numpy.ones(shape, dtype=None, order='C', *, like=None)***[source]
Return a new array of given shape and type, filled with ones.

Parameters
shapeint or sequence of ints
Shape of the new array, e.g., (2, 3) or 2.

dtypedata-type, optional
The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

order{‘C’, ‘F’}, optional, default: C
Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

likearray_like, optional
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

In [9]:
#Alternative for above soltions
import numpy as np
 
 
print(np.ones(shape=(10, 10), dtype='float') * 255) #np.ones give matrix with given shape with 1 filled as element in every row and column

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


###numpy.arange###
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
Return evenly spaced values within a given interval.

arange can be called with a varying number of positional arguments:

arange(stop): Values are generated within the half-open interval [0, stop) (in other words, the interval including start but excluding stop).

arange(start, stop): Values are generated within the half-open interval [start, stop).

arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step.

For integer arguments the function is roughly equivalent to the Python built-in range, but returns an ndarray rather than a range instance.

When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.

See the Warning sections below for more information.

Parameters
startinteger or real, optional
Start of interval. The interval includes this value. The default start value is 0.

stopinteger or real
End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

stepinteger or real, optional
Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

dtypedtype, optional
The type of the output array. If dtype is not given, infer the data type from the other input arguments.

likearray_like, optional
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.


__EXAMPLE__
>np.arange(3)
>>>array([0, 1, 2])

>np.arange(3.0)
>>>array([ 0.,  1.,  2.])

>np.arange(3,7)
>>>array([3, 4, 5, 6])

>np.arange(3,7,2)
>>>array([3, 5])

In [10]:
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


###numpy.reshape(a, newshape, order='C')####
This is used to reshape array 
a = array to be reshape 
new shape = specific shape u want


In [11]:
print(np.reshape(np.arange(10,100),(9,10)))

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


###numpy.eye###
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)###[source]

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
Nint
Number of rows in the output.

Mint, optional
Number of columns in the output. If None, defaults to N.

kint, optional
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

dtypedata-type, optional
Data-type of the returned array.

order{‘C’, ‘F’}, optional
Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

In [10]:
print(np.eye(6,6,dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


###numpy.random.rand###
Parameters
d0, d1, …, dnint, optional
The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

Returns
outndarray, shape (d0, d1, ..., dn)
Random values.

>>>np.random.rand(3,2)
>>>array([[ 0.14022471,  0.96360618],  #random
>>>>>>>  [ 0.37601032,  0.25528411],  #random
>>>>>>>  [ 0.49313049,  0.94909878]]) #random


#np.random.seed#

The seed() method is used to initialize the random number generator.

The random number generator needs a number to start with (a seed value), to be able to generate a random number.

By default the random number generator uses the current system time.

Use the seed() method to customize the start number of the random number generator.

Specifying the seed value for example ***seed(10)*** this will give the same array whenever you try to input same array matrix and seed equal to 10 other wise it will take random numbers in matrix

In [16]:
np.random.seed(10)
print(np.random.rand(30))
print(np.random.rand(10))

[0.07630829 0.77991879 0.43840923 0.72346518 0.97798951 0.53849587
 0.50112046 0.07205113 0.26843898 0.4998825  0.67923    0.80373904
 0.38094113 0.06593635 0.2881456  0.90959353 0.21338535 0.45212396
 0.93120602 0.02489923 0.60054892 0.9501295  0.23030288 0.54848992
 0.90912837 0.13316945 0.52341258 0.75040986 0.66901324 0.46775286]
[0.20484909 0.49076589 0.37238469 0.47740115 0.36589039 0.83791799
 0.76864751 0.31399468 0.57262533 0.27604905]




###numpy.random.randn###
random.randn(d0, d1, ..., dn)
Return a sample (or samples) from the “standard normal” distribution.
d0, d1, ..., dn : [int, optional]Dimension of the returned array we require, 
     If no argument is given a single Python float is returned.

  __Return__ :- Array of defined shape, filled with random floating-point samples from 
the standard normal distribution.
[What is Standard normal Distribution](https://www.youtube.com/watch?v=rzFX5NWojp0&ab_channel=StatQuestwithJoshStarmer)



In [2]:
import numpy as np
np.random.seed(20)
print(np.random.randn(10,4))

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


In [4]:
sigma = np.sqrt(9)
print(sigma)


3.0


NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

###numpy.nditer###

class numpy.nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)[source]

[nditer](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html?highlight=numpy%20nditer#numpy.nditer)

nditer itterate over each and every element of array

Parameters
opndarray or sequence of array_like
The array(s) to iterate over.

In [3]:
import numpy as np
A = np.array([[1, 4, 3],
              [5, 2, 6]])
              
for i in np.nditer(A):
    print(i)

1
4
3
5
2
6


###random.choice###

random.choice(a, size=None, replace=True, p=None)
a1-D array-like or int
If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)

sizeint or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

replaceboolean, optional
Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

p1-D array-like, optional
The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.


In [6]:
np.random.seed(42)

print(np.random.choice(range(1, 50), size=(2,3), replace=False))

[[14 46 48]
 [45 18 28]]


###numpy.diag###
numpy.diag(v, k=0)[source]
Extract a diagonal or construct a diagonal array.___

See the more detailed documentation for numpy.diagonal if you use this function to extract a diagonal and wish to write to the resulting array; whether it returns a copy or a view depends on what version of numpy you are using.

Parameters
varray_like
If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

kint, optional
Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

Returns
outndarray
The extracted diagonal or constructed diagonal array.

In [10]:
print(np.diag(np.arange(2,6,1))) #Printing Elements from arange diagonally 


[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


###numpy.save###
numpy.save(file, arr, allow_pickle=True, fix_imports=True)[source]
Save an array to a binary file in NumPy .npy format.

Parameters
filefile, str, or pathlib.Path
File or filename to which the data is saved. If file is a file-object, then the filename is unchanged. If file is a string or Path, a .npy extension will be appended to the filename if it does not already have one.

arrarray_like
Array data to be saved.

allow_picklebool, optional
Allow saving object arrays using Python pickles. Reasons for disallowing pickles include security (loading pickled data can execute arbitrary code) and portability (pickled objects may not be loadable on different Python installations, for example if the stored objects require libraries that are not available, and not all pickled data is compatible between Python 2 and Python 3). Default: True

fix_importsbool, optional
Only useful in forcing objects in object arrays on Python 3 to be pickled in a Python 2 compatible way. If fix_imports is True, pickle will try to map the new Python 3 names to the old module names used in Python 2, so that the pickle data stream is readable with Python 2


###numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')###
 Numpy.load function is to load other file and use their function and variable in current program

###Numpy.load###
numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')
 Numpy.load function is to load other file and use their function and variable in current program

In [14]:
import numpy as np

A =np.arange(12).reshape(3,4)
np.save('array.npy',A)  #saving array name A in file name as "array.npy"

B = np.load('array.npy') #Loading file "array.npy and using its matrix A in new variable "
print(B)  


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


###Numpy.savetxt###
numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)

Save as txt file

Parameters
fnamefilename or file handle
If the filename ends in .gz, the file is automatically saved in compressed gzip format. loadtxt understands gzipped files transparently.

X1D or 2D array_like
Data to be saved to a text file.

fmtstr or sequence of strs, optional
A single format (%10.5f), a sequence of formats, or a multi-format string, e.g. ‘Iteration %d – %10.5f’, in which case delimiter is ignored. For complex X, the legal options for fmt are:

a single specifier, fmt=’%.4e’, resulting in numbers formatted like ‘ (%s+%sj)’ % (fmt, fmt)

a full string specifying every real and imaginary part, e.g. ‘ %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej’ for 3 columns

a list of specifiers, one per column - in this case, the real and imaginary part must have separate specifiers, e.g. [‘%.3e + %.3ej’, ‘(%.15e%+.15ej)’] for 2 columns

delimiterstr, optional
String or character separating columns.

newlinestr, optional
String or character separating lines


###Numpy.loadtxt###
numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)

Load data from a text file.

[Details of Numpy.loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html?highlight=numpy%20loadtxt#numpy.loadtxt)



In [15]:
import numpy as np

A = np.arange(12).reshape(3,4)
np.savetxt('array.txt',A)

B = np.loadtxt('array.txt')
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


###ndarray.tolist()###

Syntax:- ndarray.tolist()

Convert NumPy array to list

In [11]:
import numpy as np

A = np.arange(12).reshape(3,4)

B = np.ndarray.tolist(A)

print(B)




[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


###Transpose Matrix###
array_n[::-1]



In [13]:
import numpy as np 

A = np.arange(12).reshape(-1,4)

print(A,"\n",)
print("----Transpose Matrix--------","\n")
print(A[::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

----Transpose Matrix-------- 

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [14]:
print(np.ones(shape=(4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


###Numpy.pad###
Use to pad the matrix 
numpy.pad(array, pad_width, mode='constant', **kwargs)
pad with surface around the matrix 

In [15]:
import numpy as np

A = np.ones(shape=(4,4),dtype=float)
print(np.pad(A, pad_width=2, constant_values=0))


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


###Slice Operation###
for Slicing an array we use ":" 
the below example slice array 
using  row and column

In [16]:
import numpy as np
 
A = np.zeros(shape=(6, 6), dtype='int')
A[::2, ::2] = 10  # This will start with (::2)0 row and skip 1 move to 2nd row and (,::2) this will start from o column and skip the first move to 2nd make them equal to 10
A[1::2, ::2] = 5 # This will start with (::2)0 row and skip 1 move to 2nd row and (,::2) this will start from o column and skip the first move to 2nd make them equal to 10
print(A)


[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


###Numpy.intersect1d###
numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
return intersect elements from 2 array with sorted 

In [17]:
import numpy as np

A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      

print(np.intersect1d(A,B))


[0 2 3]


###numpy.unique###
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)

unique elements means every element only once


In [64]:
import numpy as np


np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(A)

print(np.unique(A))

[[5 1 2 1 2]
 [9 1 9 7 5]
 [4 1 5 7 9]]
[1 2 4 5 7 9]


###Numpy.argmax###
numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
Returns the indices (index) of the maximum values along an axis.



In [18]:
import numpy as np

A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
print(np.argmax(A,axis=1)) #in first row o.4 is max value i.e on 0th postion and same for Further.

[0 2 1]


###np.sort###
numpy.sort(arr_name,axes=0:colm,1:row)


In [20]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
              
print(np.sort(A,0)) #Column Sorting
print(np.sort(A,1)) #Row Sorting

[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]
[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]


In [22]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
              
print(A[A > 8])



[ 9.99  9.99 14.99]


###Np.where###
 
 numpy.where(condition, [x, y, ]/)

 Return elements chosen from x or y depending on condition.



In [23]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
              
print(np.where(A<10,A,10))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


###Numpy.ravel###
numpy.ravel(a, order='C') 

Return a contiguous flattened array.


aarray_like
Input array. The elements in a are read in the order specified by order, and packed as a 1-D array.

order{‘C’,’F’, ‘A’, ‘K’}, optional
The elements of a are read using this index order. ‘C’ means to index the elements in row-major, C-style order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to index the elements in column-major, Fortran-style order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of axis indexing. ‘A’ means to read the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. ‘K’ means to read the elements in the order they occur in memory, except for reversing the data when strides are negative. By default, ‘C’ index order is used.



In [24]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
              
print(np.ravel(A)) #return array in list form

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


###Numpy.zeros_like###

numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

Return an array of zeros with the same shape and type as a given array.

In [26]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
              
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


###Numpy.full_like###

Return a full array with the same shape and type as a given array.



In [27]:
import numpy as np


A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
              
print(np.full_like(A,9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


###numpy.tri###

numpy.tri(N, M=None, k=0, dtype=<class 'float'>, *, like=None)[source]
An array with ones at and below the given diagonal and zeros elsewhere.

Parameters
Nint
Number of rows in the array.

Mint, optional
Number of columns in the array. By default, M is taken equal to N.

kint, optional
The sub-diagonal at and below which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.

dtypedtype, optional
Data type of the returned array. The default is float.

In [28]:
import numpy as np

print(np.tri(5,5,0))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


###Random integer or Array###



In [29]:
import numpy as np 

image = np.random.randint(
    low=0, 
    high=256, 
    size=(200, 300), 
    dtype=np.uint8
)

print(image)

[[249 167 170 ... 188 154   3]
 [138  20 194 ...  38  45  74]
 [242 108 221 ... 184  57 105]
 ...
 [180  55 112 ... 143 189 122]
 [ 21  11 118 ... 244 248 221]
 [219  87 125 ... 245 135 179]]


###Numpy.sort###

Numpy.sort(a, axis=- 1, kind=None, order=None)
Return a sorted copy of an array.

In [30]:
import numpy as np

np.random.seed(10)
image = np.random.randint(low=0, high=256, size=(3, 5), dtype=np.uint8)

image_sorted = np.sort(image)

print(image,"\n")
print("Sorted Matrix below","\n")
print(image_sorted)

[[  9  69 117 197 125]
 [156 123  76 228 255]
 [ 79   5  15 114 157]] 

Sorted Matrix below 

[[  9  69 117 125 197]
 [ 76 123 156 228 255]
 [  5  15  79 114 157]]


###np.expand_dims###

numpy.expand_dims(a, axis)

Expand the shape of an array. 

Insert a new axis that will appear at the axis position in the expanded array shape.





In [61]:
import numpy as np


A = np.array([[4, 2, 1],
              [6, 4, 2]])
              
print(A.shape)
A = np.expand_dims(A,axis=(1,3))#this implies the axis start from index 1 and till index 2
print(A.shape)

(2, 3)
(2, 1, 3, 1)


In [64]:
import numpy as np


image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image_extended = np.expand_dims(image,0)

print(image_extended.shape)


(1, 200, 300, 3)


###Numpy.append###
numpy.append(arr, values, axis=None)
Append values to the end of an array.


arrarray_like
Values are appended to a copy of this array.

valuesarray_like
These values are appended to a copy of arr. It must be of the correct shape (the same shape as arr, excluding axis). If axis is not specified, values can be any shape and will be flattened before use.

axisint, optional
The axis along which values are appended. If axis is not given, both arr and values are flattened before use.


In [78]:
import numpy as np


image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image1 = np.expand_dims(image1,0)
image2 = np.expand_dims(image2,axis=0)

images = np.append(image1,image2,0)
print(images.shape)

(2, 200, 300, 3)


###Numpy.squeeze###

numpy.squeeze(a, axis=None)

aarray_like
Input data.

axisNone or int or tuple of ints, optional
New in version 1.7.0.

Selects a subset of the entries of length one in the shape. If an axis is selected with shape entry greater than one, an error is raised.



In [83]:
import numpy as np


A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
               
print(np.squeeze(A,0)) #this will be squeeze array A with 0


[[1 2 3]
 [6 3 2]]


In [84]:
import numpy as np


A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
              
              
print(np.squeeze(A,axis=1)) #flatten row in column squeeze

[0.4 0.9 0.5 0.6]


###slicing array###

In [12]:
import numpy as np


A = np.arange(12, dtype='int').reshape(-1, 4)

print(A)
print("\n")
print(A[:,::-1])  # Bring last column to first
print("\n")
print(A[::-1,:])  # Bring last row on the top 
print("\n")
print(A[::-1,::-1]) #bring last column and last row in front 



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


Q.Extract the first channel (index 0) of this image array and print it to the console.



In [18]:
import numpy as np
 
 
np.random.seed(42)
 
image = np.random.randint(
    low=0, 
    high=256, 
    size=(1, 3, 3), 
    dtype=np.uint8
)

print(image)
print("\n")
print(image[:, :, 0])

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]]]


[[102  95 234]]


Q.Extract any array of shape (5, 5, 3) from this array and assign to the result variable.



In [21]:
import numpy as np


image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
result = image[:5,:5,:]
print(result)

[[[122  49  32]
  [155   4 151]
  [244  18 233]
  [ 13  34 237]
  [230 104 196]]

 [[244 220 200]
  [ 32 156 217]
  [ 71 119 144]
  [159  11  51]
  [ 15 115 161]]

 [[150 137 156]
  [ 79  61  46]
  [ 57 171 215]
  [ 54  63  83]
  [ 36 227 121]]

 [[ 84  70 218]
  [ 95  32 227]
  [ 34 166 173]
  [143 192  19]
  [227 120 226]]

 [[130 106  82]
  [217   0 207]
  [194 194   4]
  [ 68 195 184]
  [217 220 175]]]


###Numpy.concatenate###
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.




In [22]:
import numpy as np


A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
              
print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


In [25]:
import numpy as np


data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
                   
            
print(np.concatenate((data,target),axis=1,dtype=float))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


###numpy.column_stack###
numpy.column_stack(tup)

Stack 1-D arrays as columns into a 2-D array.

Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, just like with hstack. 1-D arrays are turned into 2-D columns first.

Parameters
tupsequence of 1-D or 2-D arrays.
Arrays to stack. All of them must have the same first dimension.

Returns
stacked2-D array
The array formed by stacking the given arrays.




In [27]:
import numpy as np


feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])


print(np.column_stack((feature1,feature2,feature3))) #1D array ko convert karta hai 2d array mein stack karke

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


###numpy.split###
numpy.split(ary, indices_or_sections, axis=0)


Split an array into multiple sub-arrays as views into ary.


aryndarray
Array to be divided into sub-arrays.

indices_or_sectionsint or 1-D array
If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.

If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in

ary[:2]

ary[2:3]

ary[3:]

If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.

In [39]:
import numpy as np


np.random.seed(42)

A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

print(A)

A1, A2 ,A3= np.split(A, [2,6], axis=1) # This will split array into 3 part which is 0:1 ,2:5 , 5:end splitting will be done on basis of column


print(A1)
print("\n")

print(A2)
print("\n")

print(A3)
print("\n")

[[0 0 4 6 2 4 1 1]
 [0 0 6 2 2 4 1 1]
 [0 0 1 3 5 5 1 1]
 [0 0 3 1 5 4 1 1]
 [0 0 2 6 1 3 1 1]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]




###numpy.count_nonzero###

numpy.count_nonzero(a, axis=None, *, keepdims=False)

This will count non zero element in an Array

In [40]:
import numpy as np


np.random.seed(42)

A = np.random.randint(low=0, high=2, size=(10, 6))

print(np.count_nonzero(A))

31


###numpy.set_printoptions###

numpy.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)

Set printing options.

These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

In [41]:
import numpy as np


np.random.seed(42)

A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


In [43]:
import numpy as np


A = np.array([1.2e-6, 1.7e-7])

print(A,"\n")
np.set_printoptions(precision=8,suppress=True)
print(A)

[0.0000012  0.00000017] 

[0.0000012  0.00000017]


###numpy.delete###

numpy.delete(arr, obj, axis=None)

Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

In [44]:
import numpy as np


np.random.seed(42)

A = np.random.randn(8, 4)

print(np.delete(A, [2], axis=1))


[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


###numpy.linalg###

[linear algebra](https://numpy.org/doc/stable/reference/routines.linalg.html?highlight=linalg#module-numpy.linalg)

In [45]:
import numpy as np


v = np.array([3, 4, -2])
print(np.linalg.norm(v))


5.385164807134504


Q. Set the Numpy option to print only ten edge elements and then print this array to the console.



In [46]:
import numpy as np


np.random.seed(42)
A = np.random.randint(10, size=(100, 30))
np.set_printoptions(edgeitems=10)
print(A)


[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]


In [1]:
import numpy as np


A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
              
print(np.mean(A))
print(np.mean(B))

4.125
3.75


###np.divide###
Divide arguments element-wise.

x1array_like
Dividend array.

x2array_like
Divisor array. If x1.shape != x2.shape, they must be broadcastable to a common shape (which becomes the shape of the output).

outndarray, None, or tuple of ndarray and None, optional
A location into which the result is stored. If provided, it must have a shape that the inputs broadcast to. If not provided or None, a freshly-allocated array is returned. A tuple (possible only as a keyword argument) must have length equal to the number of outputs.

wherearray_like, optional
This condition is broadcast over the input. At locations where the condition is True, the out array will be set to the ufunc result. Elsewhere, the out array will retain its original value. Note that if an uninitialized out array is created via the default out=N


Q. Calculate arithmetic means of these arrays (elementwise) and print result to the console.



In [3]:
import numpy as np


A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
              
print(np.divide(np.add(A, B), 2)) #By adding each element wise of array A and B and dividing by 2 

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


###Numpy.multiply###

numpy.multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) 
Multiply arguments element-wise.



In [6]:
import numpy as np


A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
              
print(np.multiply(A,B))

[[12 12 18 10]
 [30  9  2 30]]


###Numpy.sqrt###
numpy.sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) 


Return the non-negative square-root of an array, element-wise.



In [7]:
import numpy as np


A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
              
              
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


###Numpy.linspace###

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

Return evenly spaced numbers over a specified interval.

startarray_like
The starting value of the sequence.

stoparray_like
The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.

numint, optional
Number of samples to generate. Default is 50. Must be non-negative.

endpointbool, optional
If True, stop is the last sample. Otherwise, it is not included. Default is True.

retstepbool, optional
If True, return (samples, step), where step is the spacing between samples



In [10]:
import numpy as np


A = np.linspace(0, np.pi / 2, 20)

print(A)
B = np.full(shape=(20,), fill_value=1, dtype='float')


print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))


[0.         0.08267349 0.16534698 0.24802047 0.33069396 0.41336745
 0.49604095 0.57871444 0.66138793 0.74406142 0.82673491 0.9094084
 0.99208189 1.07475538 1.15742887 1.24010236 1.32277585 1.40544935
 1.48812284 1.57079633]
True


###numpy.sin###
numpy.sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) 

Trigonometric sine, element-wise.

xarray_like
Angle, in radians ( rad equals 360 degrees).

outndarray, None, or tuple of ndarray and None, optional
A location into which the result is stored. If provided, it must have a shape that the inputs broadcast to. If not provided or None, a freshly-allocated array is returned. A tuple (possible only as a keyword argument) must have length equal to the number of outputs.

wherearray_like, optional
This condition is broadcast over the input. At locations where the condition is True, the out array will be set to the ufunc result. Elsewhere, the out array will retain its original value. Note that if an uninitialized out array is created via the default out=None, locations within it where the condition is False will remain uninitialized.


In [9]:
import numpy as np


A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')


print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))

True


###numpy.dot###
Matrix multiplication

numpy.dot(a, b, out=None)
![Dot Product example](https://dcvp84mxptlac.cloudfront.net/diagrams2/equation-6-3x3-matrix-multiplication-example-pt-5.jpg)


In [11]:
import numpy as np
 
 
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
 
print(np.dot(A, B))


[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


###Numpy.linalg.det###

linalg.det(a)

To Find determinant of matrix


![Example of Matrix Determinant](https://dcvp84mxptlac.cloudfront.net/diagrams2/equation-3-determinant-of-a-3x3-matrix.png)

In [13]:
import numpy as np


A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
              
print(np.linalg.det(A))

51.999999999999986


###numpy.linalg.eig###
linalg.eig(a)

Compute the eigenvalues and right eigenvectors of a square array.

![ What is Eigen Value and Eigen Vector](https://i.ytimg.com/vi/GLVfsX5aqx8/maxresdefault.jpg)

In [14]:
import numpy as np


A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
              
              
print(np.linalg.eig(A))

(array([-9.24621125, -3.        ,  7.24621125]), array([[-6.26164716e-01, -8.94427191e-01,  8.90159406e-01],
       [-3.13082358e-01,  2.82399734e-16,  4.45079703e-01],
       [ 7.14070855e-01,  4.47213595e-01, -9.75719719e-02]]))


###numpy.linalg.inv###

linalg.inv(a)

Compute the (multiplicative) inverse of a matrix.

Given a square matrix a, return the matrix ainv satisfying dot(a, ainv) = dot(ainv, a) = eye(a.shape[0]).



In [15]:
import numpy as np


A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
              
              
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


###numpy.trace###

numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)[source]

Return the sum along diagonals of the array.

If a is 2-D, the sum along its diagonal with the given offset is returned, i.e., the sum of elements a[i,i+offset] for all i.

If a has more than two dimensions, then the axes specified by axis1 and axis2 are used to determine the 2-D sub-arrays whose traces are returned. The shape of the resulting array is the same as that of a with axis1 and axis2 removed.

Parameters
aarray_like
Input array, from which the diagonals are taken.

offsetint, optional
Offset of the diagonal from the main diagonal. Can be both positive and negative. Defaults to 0.

axis1, axis2int, optional
Axes to be used as the first and second axis of the 2-D sub-arrays from which the diagonals should be taken. Defaults are the first two axes of a.

In [16]:
import numpy as np


A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
              
              
print(np.trace(A)) #Diagonal element Sum i.e ( 5+1+(-11))

-5


Q.Transform B array to perform the matrix multiplication A x B. Then perform this multiplication and print result to the console.



In [1]:
import numpy as np


A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

print(np.dot(A, B.reshape(2, -1)))


[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


###Numpy.random.shuffle###

random.shuffle(x)

Modify a sequence in-place by shuffling its contents.



In [2]:
import numpy as np


np.random.seed(42)

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
              
              
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']
 ['004' '2.49']]


###numpy.argsort###

numpy.argsort(a, axis=- 1, kind=None, order=None)

Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

Parameters
aarray_like
Array to sort.

axisint or None, optional
Axis along which to sort. The default is -1 (the last axis). If None, the flattened array is used.

In [3]:
import numpy as np


A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

print(np.argsort(A))

[5 2 1 0 4 3]


In [5]:
import numpy as np


np.random.seed(42)
A = np.random.randn(10, 8)

np.round(A,decimals=3)
print(A)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975  0.24196227 -1.91328024
  -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037   1.46564877 -0.2257763
   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375
  -0.60170661  1.85227818]
 [-0.01349722 -1.05771093  0.82254491 -1.22084365  0.2088636  -1.95967012
  -1.32818605  0.19686124]
 [ 0.73846658  0.17136828 -0.11564828 -0.3011037  -1.47852199 -0.71984421
  -0.46063877  1.05712223]
 [ 0.34361829 -1.76304016  0.32408397 -0.38508228 -0.676922    0.61167629
   1.03099952  0.93128012]
 [-0.83921752 -0.30921238  0.33126343  0.97554513 -0.47917424 -0.18565898
  -1.10633497 -1.19620662]
 [ 0.81252582  1.35624003 -0.07201012  1.0035329   0.36163603 -0.64511975
   0.36139561  1.53803657]
 [-0.03582604  1.56464366 -2.6197451   0.8219025   0.08704707 -0.29900735
   0.09176078 -1.9

###Numpy.roots###
Return the roots of a polynomial with coefficients given in p.




In [6]:
import numpy as np

A = np.array([4,5,1])

print(np.roots(A))

[-1.   -0.25]


In [8]:
import numpy as np

Q = np.array([2,4,-5,1])
R = np.array([2,-5,1])

print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[2.28077641 0.21922359]


. QCalculate the roots of the following polynomials:

![Question](https://img-c.udemycdn.com/redactor/raw/2020-07-02_05-51-18-ccc51005deb0dd6c12ec7ace05fefcc7.JPG)

In response print these roots to the console as shown below.



Tip: Use the np.roots() function.

In [9]:
import numpy as np

Q = np.array([2,4,-5,1])
R = np.array([2,0,-5,1])

print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

###polynomial Add Sub multip###

In [10]:
import numpy as np

W = np.array([4,5,1])
Q = np.array([2,4,-5,1])

print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))




[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


###numpy.sign###
numpy.sign(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'sign'>

The sign function returns -1 if x < 0, 0 if x==0, 1 if x > 0. nan is returned for nan inputs.

For complex inputs, the sign function returns sign(x.real) + 0j if x.real != 0 else sign(x.imag) + 0j.

In [11]:
import numpy as np


A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
              
              
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]


###Datetime data type###
Using the np.arange() function, generate the following array:



['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']

In [12]:
import numpy as np

print(np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]'))


['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']


###np.datetime64###

If created from a 64-bit integer, it represents an offset from 1970-01-01T00:00:00. If created from string, the string can be in ISO 8601 date or datetime format.



In [13]:
import numpy as np

print(np.datetime64('today'))

2022-08-16


Q . Using Numpy generate all dates for mondays from January and February 2020 as an array and print result to the console.



In [1]:
import numpy as np

print(np.arange('2020-01-06', '2020-03', dtype='datetime64[D]')[::7])


['2020-01-06' '2020-01-13' '2020-01-20' '2020-01-27' '2020-02-03'
 '2020-02-10' '2020-02-17' '2020-02-24']


###char.add(x1, x2)###

Return element-wise string concatenation for two arrays of str or unicode.

Arrays x1 and x2 must have the same shape.



In [4]:
import numpy as np


A = np.array(['001', '002', '003'], dtype=str)
B = np.array(['XC', 'YC', 'ZC'], dtype=str)

print(np.char.add(A,B))

['001XC' '002YC' '003ZC']


In [7]:
import numpy as np

A = np.array(['1', '2', '3'], dtype=np.str)

A = np.char.rjust(A,3,'0')
print(A)

['001' '002' '003']


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until


###numpy.char.rjust###
char.rjust(a, width, fillchar=' ')

Return an array with the elements of a right-justified in a string of length width.

Calls str.rjust element-wise.

In [9]:
import numpy as np

A = np.array(['1', '2', '3'], dtype=str)

A = np.char.rjust(A,4,'0')  #This will add 3 zeros in above array to each element of that array
print(A)

['0001' '0002' '0003']


In [11]:
#Alternative Solution for above 
import numpy as np
 
 
A = np.array(['1', '2', '3'], dtype=str)
 
print(np.char.add('000', A))

['0001' '0002' '0003']


###np.char.zfill###
 This fill zero in provided Array

In [14]:
import numpy as np
 
 
A = np.array(['1', '2', '3'], dtype=str)
 
print(np.char.zfill(A, 4)) #in Array A fill zero till 3 postition

['0001' '0002' '0003']


###numpy.char.split###

char.split(a, sep=None, maxsplit=None)

For each element in a, return a list of the words in the string, using sep as the delimiter string.

Calls str.split element-wise.

Parameters
aarray_like of str or unicode
sepstr or unicode, optional
If sep is not specified or None, any whitespace string is a separator.

maxsplitint, optional
If maxsplit is given, at most maxsplit splits are done.

In [17]:
import numpy as np


A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=str)
              
print(np.char.split(A,maxsplit=2))

[[list(['PLW', 'CDR', '11B TEN']) list(['AMC', 'LPP'])]
 [list(['CDR', 'PKO', 'KGH']) list(['CCC', 'QMK'])]]


###numpy.char.strip###

char.strip(a, chars=None)

For each element in a, return a copy with the leading and trailing characters removed.

Calls str.strip element-wise.

Parameters
aarray-like of str or unicode
charsstr or unicode, optional
The chars argument is a string specifying the set of characters to be removed. If omitted or None, the chars argument defaults to removing whitespace. The chars argument is not a prefix or suffix; rather, all combinations of its values are stripped.

Returns
outndarray

###numpy.char.replace###

char.replace(a, old, new, count=None)

For each element in a, return a copy of the string with all occurrences of substring old replaced by new.

Calls str.replace element-wise.

Parameters
aarray-like of str or unicode
old, newstr or unicode
countint, optional
If the optional argument count is given, only the first count occurrences are replaced.

In [18]:
import numpy as np


A = np.array([['#summer#time#mood'],
              ['#sport#time']])
              
              
A = np.char.strip(np.char.replace(A,"#"," "))
print(A)

[['summer time mood']
 ['sport time']]


###numpy.char.count###

char.count(a, sub, start=0, end=None)

Returns an array with the number of non-overlapping occurrences of substring sub in the range [start, end].

Calls str.count element-wise.

Parameters
aarray_like of str or unicode
substr or unicode
The substring to search for.

start, endint, optional
Optional arguments start and end are interpreted as slice notation to specify the range in which to count.

In [19]:
import numpy as np


A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
              
print(np.char.count(A,"time"))

[[1 0]
 [1 1]
 [0 0]]


In [23]:
import numpy as np


text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""

lines = text.splitlines()
print("\n---------------------",lines)
lines = [line.split('\t') for line in lines]
print("\n",lines,'----------')
result = np.array(lines, dtype=np.str)
print(result)


--------------------- ['ALIOR\tPLALIOR00045\t88 860 000\t1 386 216 000\t0,891\t2,16\t14', 'CCC\tPLCCC0000016\t27 918 000\t1 292 603 400\t0,831\t5,28\t42', 'CDPROJEKT\tPLOPTTC00011\t67 348 000\t22 864 646 000\t14,702\t7,39\t7', 'CYFRPLSAT\tPLCFRPT00013\t275 301 000\t6 854 994 900\t4,408\t1,17\t14', 'DINOPL\tPLDINPL00011\t47 937 000\t8 916 282 000\t5,733\t9,13\t12', 'JSW\tPLJSW0000015\t52 636 000\t716 902 320\t0,461\t1,51\t24', 'KGHM\tPLKGHM000017\t136 410 000\t9 881 540 400\t6,354\t4,78\t8', 'LOTOS\tPLLOTOS00025\t86 543 000\t5 609 717 260\t3,607\t2,91\t16', 'LPP\tPLLPP0000011\t1 306 000\t7 444 200 000\t4,787\t1,43\t19', 'MBANK\tPLBRE0000012\t12 997 000\t2 830 746 600\t1,820\t0,42\t24', 'ORANGEPL\tPLTLKPL00017\t647 357 000\t4 285 503 340\t2,756\t1,16\t13', 'PEKAO\tPLPEKAO00016\t176 379 000\t9 619 710 660\t6,185\t5,27\t9', 'PGE\tPLPGER000010\t796 776 000\t3 561 588 720\t2,290\t2,88\t18', 'PGNIG\tPLPGNIG00014\t1 624 608 000\t6 072 784 704\t3,905\t1,56\t12', 'PKNORLEN\tPLPKN0000018\t289 04

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


In [24]:
import numpy as np
 
 
np.set_printoptions(linewidth=150)
result = np.array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891', '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831', '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000', '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900', '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733', '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461', '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354', '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607', '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787', '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820', '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647 357 000', '4 285 503 340', '2,756', '1,16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176 379 000', '9 619 710 660', '6,185', '5,27', '9'],
       ['PGE', 'PLPGER000010', '796 776 000', '3 561 588 720', '2,290', '2,88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1 624 608 000', '6 072 784 704', '3,905', '1,56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289 049 000', '17 701 360 760', '11,382', '12,44', '8'],
       ['PKOBP', 'PLPKO0000016', '857 593 000', '18 807 014 490', '12,093', '10,49', '9'],
       ['PLAY', 'LU1642887738', '114 151 000', '3 696 209 380', '2,377', '1,47', '16'],
       ['PZU', 'PLPZU0000011', '568 305 000', '17 515 160 100', '11,262', '6,64', '6'],
       ['SANPL', 'PLBZ00000044', '33 207 000', '5 213 499 000', '3,352', '1,91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1 043 590 000', '1 252 308 000', '0,805', '1,21', '33']], dtype='<U14')
 
result = np.char.replace(result, ' ', '')
result = np.char.replace(result, ',', '.')
print(result)

[['ALIOR' 'PLALIOR00045' '88860000' '1386216000' '0.891' '2.16' '14']
 ['CCC' 'PLCCC0000016' '27918000' '1292603400' '0.831' '5.28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67348000' '22864646000' '14.702' '7.39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275301000' '6854994900' '4.408' '1.17' '14']
 ['DINOPL' 'PLDINPL00011' '47937000' '8916282000' '5.733' '9.13' '12']
 ['JSW' 'PLJSW0000015' '52636000' '716902320' '0.461' '1.51' '24']
 ['KGHM' 'PLKGHM000017' '136410000' '9881540400' '6.354' '4.78' '8']
 ['LOTOS' 'PLLOTOS00025' '86543000' '5609717260' '3.607' '2.91' '16']
 ['LPP' 'PLLPP0000011' '1306000' '7444200000' '4.787' '1.43' '19']
 ['MBANK' 'PLBRE0000012' '12997000' '2830746600' '1.820' '0.42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647357000' '4285503340' '2.756' '1.16' '13']
 ['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 

###NUmpy.char.startswith###

char.startswith(a, prefix, start=0, end=None)

Returns a boolean array which is True where the string element in a starts with prefix, otherwise False.

Calls str.startswith element-wise.

Parameters
aarray_like of str or unicode
prefixstr
start, endint, optional
With optional start, test beginning at that position. With optional end, stop comparing at that position.

In [31]:
import numpy as np


np.set_printoptions(linewidth=150)
result = np.array([['ALIOR', 'PLALIOR00045', '88860000', '1386216000', '0.891', '2.16', '14'],
       ['CCC', 'PLCCC0000016', '27918000', '1292603400', '0.831', '5.28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67348000', '22864646000', '14.702', '7.39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275301000', '6854994900', '4.408', '1.17', '14'],
       ['DINOPL', 'PLDINPL00011', '47937000', '8916282000', '5.733', '9.13', '12'],
       ['JSW', 'PLJSW0000015', '52636000', '716902320', '0.461', '1.51', '24'],
       ['KGHM', 'PLKGHM000017', '136410000', '9881540400', '6.354', '4.78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86543000', '5609717260', '3.607', '2.91', '16'],
       ['LPP', 'PLLPP0000011', '1306000', '7444200000', '4.787', '1.43', '19'],
       ['MBANK', 'PLBRE0000012', '12997000', '2830746600', '1.820', '0.42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647357000', '4285503340', '2.756', '1.16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6'],
       ['SANPL', 'PLBZ00000044', '33207000', '5213499000', '3.352', '1.91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1043590000', '1252308000', '0.805', '1.21', '33']], dtype='<U12')
       
stock_startwith_P = result[np.char.startswith(result[:,0], 'P')]
print(stock_startwith_P)

[['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289049000' '17701360760' '11.382' '12.44' '8']
 ['PKOBP' 'PLPKO0000016' '857593000' '18807014490' '12.093' '10.49' '9']
 ['PLAY' 'LU1642887738' '114151000' '3696209380' '2.377' '1.47' '16']
 ['PZU' 'PLPZU0000011' '568305000' '17515160100' '11.262' '6.64' '6']]


###numpy.delete###

numpy.delete(arr, obj, axis=None)

Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

In [1]:
import numpy as np


np.set_printoptions(linewidth=160, suppress=True)

wig_games = np.array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
       
wig_games = np.delete(wig_games, [3, 4, 5, 9], axis=1)
print(wig_games)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


###numpy.mean###
numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

Compute the arithmetic mean along the specified axis.

Returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. float64 intermediate and return values are used for integer inputs.

Parameters
aarray_like
Array containing numbers whose mean is desired. If a is not an array, a conversion is attempted.

axisNone or int or tuple of ints, optional
Axis or axes along which the means are computed. The default

In [2]:
import numpy as np


playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
       
print(np.round(playway_values.mean(axis=0), 2))


[  283.14   295.25   268.69   282.3  48688.05]


Add Column in table of max - min

In [3]:
import numpy as np


np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
       
max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    


playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])


From this array extract the first 10 rows with the highest volume sorted in descending order.



In [4]:
import numpy as np


np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
       
print(playway_values[playway_values[:, 4].argsort()[::-1]][:10])


[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


Exercise 101
Solve the following system of equations using the Numpy package:

![image Q](https://img-c.udemycdn.com/redactor/raw/2020-07-07_07-30-54-3efdf76400720be010142591d7184209.JPG)

Print result to the console as shown below.



In [5]:
import numpy as np

A = np.array([[5, -3], [1, -2]])
B = np.array([[21], [7]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
print(f'x = {x:.2f}\ny = {y:.2f}')

x = 3.00
y = -2.00
